name: new Domain about data daily Tracker
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  track-domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

        
      - name: Run Domain Tracker
        run: python domain_google_about_batch.py
        
      - name: Commit Results
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update new domain borndate results $(date +'%Y-%m-%d')" || exit 0
          git push
