name: Historical Data Import

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  import_historical_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 psutil gitpython

      # 克隆历史数据仓库
      - name: Clone historical data repository
        run: |
          # 增加克隆深度，确保获取足够的历史记录
          git clone --depth=500 https://github.com/adysec/top_1m_domains.git historical_data
          echo "历史数据仓库克隆完成"

      # 提取历史数据并准备提交列表
      - name: Prepare commit list
        run: |
          mkdir -p historical_extracts
          cd historical_data
          
          # 获取2024年6月7日之后的提交记录，使用更精确的日期格式
          git log --pretty=format:"%H %cs" --after="2024-06-06T00:00:00" > ../historical_commits.txt
          
          # 检查提交记录数量
          commit_count=$(wc -l < ../historical_commits.txt)
          echo "找到 $commit_count 条提交记录"
          
          if [ $commit_count -lt 200 ]; then
            echo "警告：提交记录数量少于预期（200+），可能需要增加克隆深度或检查日期过滤条件"
          fi
          
          cd ..
          echo "提交列表准备完成"

      # 处理每个提交
      - name: Process commits
        run: |
          while read -r commit_hash commit_date; do
            echo "处理 $commit_date 的提交 $commit_hash"
            
            # 检出特定提交
            cd historical_data
            git checkout -f $commit_hash
            
            # 如果存在zip文件，解压并复制到对应日期的目录
            if [ -f "tranco.zip" ]; then
              mkdir -p ../historical_extracts/$commit_date
              cp tranco.zip ../historical_extracts/$commit_date/
              cd ../
              
              # 直接处理这个提交
              python -c "import sys; sys.path.append('.'); from import_historical_data import process_single_commit; process_single_commit('$commit_hash', '$commit_date')"
              
              # 检查处理结果
              if [ $? -eq 0 ]; then
                echo "成功处理 $commit_date 的数据"
              else
                echo "处理 $commit_date 的数据失败"
              fi
            else
              cd ../
              echo "提交 $commit_hash ($commit_date) 中没有找到 tranco.zip 文件"
            fi
            
          done < historical_commits.txt
          
          echo "历史数据处理完成"

      # 导入历史数据
      - name: Import historical data
        run: |
          python import_historical_data.py
          echo "历史数据导入完成"

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          # 移除 domain_rank.db，只提交 CSV 文件
          git add domains_rankings.csv domains_first_seen.csv
          git commit -m "Import historical domain rank data" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Delete temporary files
        run: |
          rm -rf historical_data
          rm -rf historical_extracts