name: Historical Data Import

on:
  workflow_dispatch:  # 仅允许手动触发
    inputs:
      start_date:
        description: '开始日期 (YYYY-MM-DD)'
        required: false
        default: '2024-06-08'
      end_date:
        description: '结束日期 (YYYY-MM-DD)'
        required: false
        default: ''
      max_commits:
        description: '单次运行最大处理提交数'
        required: false
        default: '50'

jobs:
  import_historical_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 psutil gitpython pandas pyarrow

      # 创建辅助脚本
      - name: Create helper scripts
        run: |
          python create_helper_scripts.py

      # 准备提交列表
      - name: Prepare commit list
        run: |
          python prepare_commits.py --start-date "${{ github.event.inputs.start_date }}" --end-date "${{ github.event.inputs.end_date }}"

      # 处理每个提交
      - name: Process commits
        run: |
          python process_commits.py --max-commits "${{ github.event.inputs.max_commits }}"

      # 导入历史数据
      - name: Import historical data
        run: |
          python import_historical_data.py
          echo "历史数据导入完成"

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add domains_rankings.parquet domains_first_seen.parquet
          git commit -m "Import historical domain rank data" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main