name: Historical Data Import

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  import_historical_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 psutil gitpython pandas pyarrow

      # 克隆历史数据仓库
      - name: Clone historical data repository
        run: |
          # 增加克隆深度，确保获取足够的历史记录
          git clone --depth=500 https://github.com/adysec/top_1m_domains.git historical_data
          echo "历史数据仓库克隆完成"

      # 修改工作流以按时间顺序处理所有提交
      - name: Prepare commit list
        run: |
          mkdir -p historical_extracts
          cd historical_data
          
          # 获取2024年6月8日之后的提交记录，使用更精确的日期格式
          git log --pretty=format:"%H %cs" --after="2024-06-07T23:59:59" > ../historical_commits_unsorted.txt
          
          # 按日期排序（从早到晚）
          sort -k2 ../historical_commits_unsorted.txt > ../historical_commits.txt
          
          # 检查提交记录数量
          commit_count=$(wc -l < ../historical_commits.txt)
          echo "找到 $commit_count 条提交记录"
          
          if [ $commit_count -lt 200 ]; then
            echo "警告：提交记录数量少于预期（200+），可能需要增加克隆深度或检查日期过滤条件"
          fi
          
          cd ..
          echo "提交列表准备完成"

      # 处理每个提交
      - name: Process commits
        run: |
          # 配置Git以允许推送
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 如果没有提交记录，跳过处理
          if [ ! -s historical_commits.txt ]; then
            echo "没有新的提交记录需要处理"
            exit 0
          fi
          
          # 记录最后处理的日期
          LAST_PROCESSED_DATE=""
          
          while read -r commit_hash commit_date; do
            echo "处理 $commit_date 的提交 $commit_hash"
            
            # 检出特定提交
            cd historical_data
            git checkout -f $commit_hash
            
            # 如果存在zip文件，解压并复制到对应日期的目录
            if [ -f "tranco.zip" ]; then
              mkdir -p ../historical_extracts/$commit_date
              cp tranco.zip ../historical_extracts/$commit_date/
              cd ../
              
              # 直接处理这个提交
              python -c "import sys; sys.path.append('.'); from import_historical_data import process_single_commit; process_single_commit('$commit_hash', '$commit_date')"
              
              # 检查处理结果
              if [ $? -eq 0 ]; then
                echo "成功处理 $commit_date 的数据"
                # 更新最后处理的日期
                LAST_PROCESSED_DATE=$commit_date
                # 保存最后处理的日期到文件
                echo $LAST_PROCESSED_DATE > last_processed_date.txt
                # 提交最后处理日期文件
                git add last_processed_date.txt
                git commit -m "更新最后处理日期: $LAST_PROCESSED_DATE" || echo "No changes to commit"
                git push || echo "Failed to push last processed date"
              else
                echo "处理 $commit_date 的数据失败"
              fi
            else
              cd ../
              echo "提交 $commit_hash ($commit_date) 中没有找到 tranco.zip 文件"
            fi
            
          done < historical_commits.txt
          
          echo "历史数据处理完成，最后处理的日期: $LAST_PROCESSED_DATE"

      # 删除临时文件
      - name: Delete temporary files
        run: |
          rm -rf historical_data
          rm -rf historical_extracts

      # 导入历史数据
      - name: Import historical data
        run: |
          python import_historical_data.py
          echo "历史数据导入完成"

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          # 移除 domain_rank.db，只提交 Parquet 文件
          git add domains_rankings.parquet domains_first_seen.parquet
          git commit -m "Import historical domain rank data" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main