name: Daily Domain Rank Update

on:
  # schedule:
    # - cron: '0 0 * * *'  # 每天 UTC 00:00 (北京时间 08:00) 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 psutil gitpython pandas pyarrow

      - name: Download zip file
        run: |
          mkdir -p data
          wget https://tranco-list.eu/top-1m.csv.zip -O data/tranco.zip

      - name: Run the domain update script
        run: python your_script_name.py
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Install analysis dependencies
        run: |
          pip install pandas matplotlib
          
      # 添加排名变化分析步骤
      - name: Run rank analysis
        run: |
          # 检查是否需要运行周报或月报
          DAY_OF_WEEK=$(date +%u)
          DAY_OF_MONTH=$(date +%d)
          
          if [ "$DAY_OF_MONTH" = "01" ]; then
            echo "执行月度分析报告"
            python rank_change_analyzer.py --period monthly
          elif [ "$DAY_OF_WEEK" = "1" ]; then
            echo "执行周度分析报告"
            python rank_change_analyzer.py --period weekly
          else
            echo "今天不是计划的报告日期，跳过排名分析"
          fi

      - name: Save new domains to CSV
        run: |
          # 创建 CSV 文件 (假设你的 Python 脚本会返回一个新域名的列表)
          echo "Domain" > new_domains.csv  # 添加表头
          #假设 Python 脚本输出的是每行一个域名的文本文件 new_domains.txt
          if [ -f "new_domains.txt" ]; then # 如果存在new_domains.txt才执行后续操作
            while IFS= read -r domain; do
              echo "$domain" >> new_domains.csv
            done < new_domains.txt
          else
            echo "No new domains found." # 如果不存在new_domains.txt, 则输出提示信息
          fi

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add  new_domains.txt domains_rankings.parquet domains_first_seen.parquet
          
          # 添加新域名目录
          if [ -d "new_domains" ]; then
            git add new_domains/
          fi
          
          # 添加报告文件夹（如果存在）
          if [ -d "reports" ]; then
            git add reports/
          fi
          
          git commit -m "Daily update of domain rank database and new domains" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # 或者你的主分支

      - name: Delete temporary files
        run: |
          rm data/tranco.zip # 删除zip文件
