name: Test Import Tools

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'create_helper_scripts.py'
      - 'import_historical_data.py'

jobs:
  test_import_tools:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 psutil gitpython pandas pyarrow
      
      - name: Run test workflow
        run: |
          # Create test script
          cat > test_workflow.sh << 'EOF'
          #!/bin/bash
          
          echo "=== Testing Historical Data Import Tools ==="
          echo ""
          
          # Step 1: Generate helper scripts
          echo "Step 1: Generating helper scripts..."
          python create_helper_scripts.py
          echo ""
          
          # Step 2: Prepare a small list of commits for testing
          echo "Step 2: Preparing commit list with a small date range..."
          python prepare_commits.py --start-date 2024-06-08 --end-date 2024-06-10
          echo ""
          
          # Step 3: Process a limited number of commits
          echo "Step 3: Processing a limited number of commits..."
          python process_commits.py --max-commits 3
          echo ""
          
          # Step 4: Import the processed data
          echo "Step 4: Importing processed data..."
          python import_data.py
          echo ""
          
          # Step 5: Verify results
          echo "Step 5: Verifying results..."
          echo "Checking for output files:"
          
          if [ -f "domains_rankings.parquet" ]; then
              echo "- domains_rankings.parquet: FOUND"
          else
              echo "- domains_rankings.parquet: NOT FOUND"
          fi
          
          if [ -f "domains_first_seen.parquet" ]; then
              echo "- domains_first_seen.parquet: FOUND"
          else
              echo "- domains_first_seen.parquet: NOT FOUND"
          fi
          
          if [ -f "last_processed_date.txt" ]; then
              echo "- last_processed_date.txt: FOUND"
              echo "  Last processed date:"
              cat "last_processed_date.txt"
          else
              echo "- last_processed_date.txt: NOT FOUND"
          fi
          
          echo ""
          echo "=== Test Complete ==="
          EOF
          
          # Make script executable
          chmod +x test_workflow.sh
          
          # Run the test script
          ./test_workflow.sh
      
      - name: Push artifacts
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main